---
title: "Early underdetected dissemination across countries followed by extensive local transmission propelled the 2022 mpox epidemic"
author: "Miguel I Paredes, Nashwa Ahmed, Marlin Figgins, Vittoria Colizza, Philippe Lemey, John T McCrone, Nicola Müller, Cécile Tran-Kiem, Trevor Bedford"
doi: "https://doi.org/10.1101/2023.07.27.23293266"
short_cite: "Paredes et al. 2023. medRxiv."
date: "2023-10-05"
---

## Abstract

The World Health Organization declared mpox a public health emergency of international concern in July 2022. To investigate global mpox transmission and quantify the effect of population-level interventions on controlling spread, we built phylogeographic and phylodynamic models to analyze MPXV genomes from five global regions together with air traffic and epidemiological data. Our models reveal community transmission prior to detection, changes in case-reporting throughout the epidemic, and a large degree of transmission heterogeneity. We find that viral introductions played a limited role in prolonging spread after initial dissemination, suggesting that travel bans would have had only a minor impact. We find that mpox transmission in North America began declining before more than 10% of high-risk individuals in the USA had vaccine-induced immunity. Given that cases quickly declined after detection most likely due to behavioral modifications, our findings highlight the importance of broader routine specimen screening surveillance for emerging infectious diseases.
